### ISSUE TITLE
createShadowRoot 方法在浏览器中有warning

### ISSUE THREAD

**Issue by lesonky** [saucxs/watermark-dom#18]
[Deprecation] Element.createShadowRoot is deprecated and will be removed in M73, around March 2019. Please use Element.attachShadow instead.

这个插件用了 createShadowRoot 方法来添加 shadowdom 这个方法现在快要过期了,希望更新一下方法

3Q

**Comment by saucxs** [comment]
@lesonky 不好意思，最近有点忙。
![Shadow DOM](https://user-images.githubusercontent.com/17644544/59320143-d505ff80-8cff-11e9-80f3-54f02fa2712f.png)
目前的shadom dom支持并不是很好，但是我已经做了兼容处理：
`
 /*判断浏览器是否支持createShadowRoot方法*/
            if(typeof otdiv.createShadowRoot === 'function'){
                shadowRoot = otdiv.createShadowRoot();
            }else{
                shadowRoot = otdiv;
            }
`
你的提议还是不错的，使用attachShadow 代替 createShadowRoot 。3Q
