### ISSUE TITLE
loadMark多次调用时defaultSettings变量的复用问题

### ISSUE THREAD

**Issue by shellphon** [saucxs/watermark-dom#23]
看了源码，loadMark是水印产生的主要逻辑，resize等事件会多次调用loadMark，而loadMark里对于defaultSettings的使用有点问题，https://github.com/saucxs/watermark-dom/blob/master/watermark.js#L134~L142 当多次调用loadMark时，实际上后一次的计算处理拿到的一些关键值不再是一开始声明的初始化值，这将导致resize触发后，一些变量计算不再准确，甚至出现NaN的情况，demo里也可以发现问题，在页面最大化到变回小窗口时，水印有丢失的情况（计算错误导致）

**Comment by saucxs** [comment]
谢谢你的支出，问题已经解决，请用最新的代码查看，watermark-dom版本升级到2.1.0。 @shellphon
