### ISSUE TITLE
页面有滚动条问题

### ISSUE THREAD

**Issue by xinqian598188460** [saucxs/watermark-dom#24]
当页面有滚动条的时候，发现水印下方无法显示，我觉得应该使用fixed定位。

**Comment by saucxs** [comment]
能给出具体的描述或者截图，或者外网地址我看一下

**Comment by saucxs** [comment]
@xinqian598188460 ，我试了一个很长的页面，有滚动条，地址：https://juejin.im/post/5cb686f451882532c1535199
![juejin im_post_5cb686f451882532c1535199](https://user-images.githubusercontent.com/17644544/62441932-abf66e00-b788-11e9-9119-bc21020c627e.png)
