### ISSUE TITLE
vue版本需求

### ISSUE THREAD

**Issue by moonose** [saucxs/watermark-dom#25]
相当棒的水印应用，大神能做个vue版本吗？

**Comment by saucxs** [comment]
谢谢你的关注，已经最简单的方式实现，无论是vue，react等框架，只需要两步：1、import watermark from 'watermark-dom'; 2、watermark.load({ watermark_txt: "水印内容" })。没有必要区分vue还是react，因为我这个仅操作dom一次，性能已经优化了很多，后续还会继续优化和更新。
