### ISSUE TITLE
是否可以支持固定区域加水印

### ISSUE THREAD

**Issue by nqmysb** [saucxs/watermark-dom#26]
是否可以支持固定一个区域加水印，滚动滚动条，水印跟着该区域

**Comment by saucxs** [comment]
你可以换个思路：在固定区域利用组件的形式加载，在组件中使用水印。

**Comment by nqmysb** [comment]
> 你可以换个思路：在固定区域利用组件的形式加载，在组件中使用水印。
你好，首先非常感谢你回复我，你提到的这个思路我尝试过 ，用watermark_parent_node:node   属性挂载元素下面  但是这样如果滚动滚动条 水印也不是跟着滚动的   就会导致滚动时  水印覆盖不了的情况  好像你这个水印是生成之后是fixed 定位的
