### ISSUE TITLE
插件设定就是不支持滚屏的吗

### ISSUE THREAD

**Issue by ishwy** [saucxs/watermark-dom#27]

**Comment by saucxs** [comment]
滚屏是什么意思？详细描述一下

**Comment by ishwy** [comment]
就是现在看demo都是一个页面的,  如果页面支持滚动条的话,  就不会铺满整个屏幕,, 永远只有一个屏的水印

**Comment by saucxs** [comment]
谢谢你的提出，新功能已经加上，请用最新的代码查看，watermark-dom版本升级到2.1.0。
