### ISSUE TITLE
watermark_parent_node不管用

### ISSUE THREAD

**Issue by Tianruo** [saucxs/watermark-dom#28]
挂载的父节点属性无作用，结果还是挂载到了body上面

系统：windows
浏览器：chrome
框架：react

**Comment by sunweiconfidence** [comment]
我的也是不起作用：
index.js
/*初始化水印*/
watermark.init({
    watermark_txt: "测试，1021002301，测试 10.157.182.139",
    watermark_parent_node: "div#test"
});
/*加载水印*/
watermark.load({
    watermark_txt: "测试，1021002301，测试 10.157.182.139",
    watermark_parent_node: "div#test"

});
/*移除水印*/
document.getElementById('remove-watermark').addEventListener("click", function() {
    watermark.remove();
}, true)

/*添加水印*/
document.getElementById('add-watermark').addEventListener("click", function() {
    watermark.load({
        watermark_txt: "测试，1021002301，测试 10.157.182.139",
        watermark_parent_node: "div#test"
    });
}, true)

index.html如下：
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>watermark-simple</title>
</head>

<body>
    <div style="width: 800px;margin: 0 auto;text-align: center">
        <p style="font-size: 24px;">测试页面-watermark-simple</p>
        <p>
            <a style="cursor: pointer;border: 1px solid #5579ee;padding: 6px
                    16px" id="remove-watermark">移除水印</a>
            <a style="cursor: pointer;border: 1px solid #5579ee;margin-left:
                    40px;padding: 6px 16px" id="add-watermark">添加水印</a>
        </p>
        <a title="songEagle" href="http://www.chengxinsong.cn" target="_blank">
        </a>
        <div id="test" style="width:200;height:300;"></div>
        <p>
            <a style="font-size: 24px;" href="https://github.com/saucxs/watermark-dom" target="_blank">watermark源代码</a>
        </p>
    </div>
</body>

<script src="../watermark.js"></script>
<script src="./index.js"></script>

</html>

**Comment by zhuwenqi001** [comment]
这个值是实际的html节点，比如document.getElementById('#test')

**Comment by saucxs** [comment]
该问题已经解决，请更新到2.2.0 版本。
使用例子，比如：
`watermark.load({ watermark_parent_node: "watermark-parent", watermark_txt: "saucxs，1021002301，测试水印，100101010111101" });`
详细见源码下：/examples/examples-simple文件为一个简单使用例子。 @Tianruo @sunweiconfidence
