### ISSUE TITLE
水印可以被隐藏

### ISSUE THREAD

**Issue by maqingbo** [saucxs/watermark-dom#29]
生成的水印都带有一个 id，虽然不能在元素本身上修改样式，但因为这个 id，就可以另外写新样式，然后水印会消失。

![watermark-dom](https://user-images.githubusercontent.com/20136852/63397710-16044980-c3fe-11e9-8338-05e15f3e53a8.png)

**Comment by saucxs** [comment]
道高一尺魔高一丈

**Comment by maqingbo** [comment]
@saucxs 你好，控制台里面添加的 css 属性属于外联样式，是不是可以在初始化时将常见的可以隐藏元素的 css 方法写成内联样式，这样即使新增也没用。

**Comment by inooNgt** [comment]
@saucxs http://www.chengxinsong.cn/post/34里的水印动态变化的dom结构是通过设一个定时器然后不停的调用init和remove方法完成吗？有相关代码吗

**Comment by saucxs** [comment]
@inooNgt 定时器进行不断load方法就行。一次只操作一次dom结构。代码事例可以参考examples文件里的examples-setInterval的例子。
