### ISSUE TITLE
水印图层会撑开默认页面宽度

### ISSUE THREAD

**Issue by dyh333** [saucxs/watermark-dom#30]
![image](https://user-images.githubusercontent.com/1221313/66748113-f5fe7d00-eeb8-11e9-98e2-3feff65bad87.png)

如图，由于第一行最后一个水印宽度超过页面最大宽度，导致会撑开出现水平滚动条。希望能优化当剩余宽度不够放下一个水印时，就换行。

感谢大佬

**Comment by rumenxiaozi** [comment]
+! 遇见相同的问题，高度也被撑开了

**Comment by jixiang155** [comment]
![image](https://user-images.githubusercontent.com/19303259/67351856-0da4c800-f581-11e9-8bb7-4931261ac5e6.png)
源码的这个条件运算符后面写反了吧

**Comment by saucxs** [comment]
已经更新到2.1.1版本，已经修复，你查看一下是否OK？ @dyh333 @rumenxiaozi @jixiang155

**Comment by JeanZhao** [comment]
已经更新到2.2.0，但是高度还是被撑开了
