### ISSUE TITLE
水印显示不全

### ISSUE THREAD

**Issue by ydCao** [saucxs/watermark-dom#32]
水印显示不全，页面右侧和下侧会留一部分空白，并不会填满

**Comment by Altamill** [comment]
有同样的问题，貌似还没解决。右侧和下侧都无法填充

**Comment by saucxs** [comment]
该问题已经解决，**npm请更新到2.2.0 版本。本地引用请使用最新的源码**。现在使用的是在水印区域进行居中处理，这样在视觉上更加符合审美。 @ydCao @Altamill
