### ISSUE TITLE
水印图层会撑开页面高度

### ISSUE THREAD

**Issue by JeanZhao** [saucxs/watermark-dom#33]
var page_height = Math.max(watermark_hook_element.scrollHeight,watermark_hook_element.clientHeight,document.documentElement.clientHeight);

这里获取的是页面最大高度，感觉应该是获取加水印容器的高度吧？为什么要加上 document.documentElement.clientHeight  ？

**Comment by paperscz** [comment]
同存撑开了页面高度的问题

**Comment by JeanZhao** [comment]
我用的这个方案解决的：
直接引用watermark.js文件，并把我上面提到的那行代码改成：
var page_height = Math.max(watermark_hook_element.scrollHeight,watermark_hook_element.clientHeight);
就可以了。

**Comment by saucxs** [comment]
在2.2.1版本中已经修复，谢谢指出，以后可以直接提 pull request @JeanZhao @paperscz

**Comment by guoshengbo** [comment]
兄弟 2.2.1没改啊，看了源码 你还是原来的代码啊

**Comment by JeanZhao** [comment]
> 兄弟 2.2.1没改啊，看了源码 你还是原来的代码啊
源码调整了，但是没有用我给的代码。
你是不是没有设置watermark_parent_node？我没设置也有这问题。你可以试试我上面的代码方案。
