### ISSUE TITLE
点击介绍里写的的官网地址会重定向到另外一个网站

### ISSUE THREAD

**Issue by lilywang711** [saucxs/watermark-dom#34]
http://www.chengxinsong.cn/home => https://www.mwcxs.top/home

**Comment by lilywang711** [comment]
emmm 才知道这就是 主动重定向的，，但是打开过去太像一个广告网站了

**Comment by saucxs** [comment]
这个站点的服务器到期了未处理，导致nginx的重定向，现已经修复，丢失了一些数据。
