### ISSUE TITLE
页面F12调试模式，拖到最小再展开，水印消失

### ISSUE THREAD

**Issue by mushroomlb** [saucxs/watermark-dom#49]
页面F12调试模式，拖到最小再展开，水印消失

**Comment by lilegang1589** [comment]
水印是通过计算得到的，拖到最小时计算出来的水印列是NaN，就无法计算了，可以通过设置页面最小宽度解决这个问题

**Comment by mushroomlb** [comment]
现在是不用拖到0，就已经不显示了，建议在内部当resize时增加判断
