### ISSUE TITLE
请求增加 d.ts 类型声明文件

### ISSUE THREAD

**Issue by whinc** [saucxs/watermark-dom#61]
如果再 TypeScript 项目中使用，没有类型信息提示，期望增加 d.ts 文件

**Comment by shlroland** [comment]
> 如果再 TypeScript 项目中使用，没有类型信息提示，期望增加 d.ts 文件

已添加到@types/watermark-dom，直接安装就行了

**Comment by whinc** [comment]
#

> > 如果再 TypeScript 项目中使用，没有类型信息提示，期望增加 d.ts 文件
> 
> 已添加到@types/watermark-dom，直接安装就行了

👍
