### ISSUE TITLE
关于npm包的疑问

### ISSUE THREAD

**Issue by shinken008** [saucxs/watermark-dom#69]
## 发包跟源码的区别
发的包和源码差异很大，npm 包里 package.json 也不一样，建议希望提供一个 .min 文件和一个不压缩的文件。希望统一规范

## webpack 5不兼容
看了下包压缩后的代码，请问这是使用什么方式 build 的包？有点像是用 webpack 打包出来的 copy 过来的？

**Comment by saucxs** [comment]
还在优化和优化一些功能，后边会统一规范的，直接压缩的文件打包的，后边会更规范和便捷。
