### ISSUE TITLE
在 vue3 项目里使用报错

### ISSUE THREAD

**Issue by hooray** [saucxs/watermark-dom#87]
![image](https://user-images.githubusercontent.com/1574903/135677368-1a6d0f52-330d-4d8f-9dde-d77e05f5d020.png)

**Comment by QbjGKNick** [comment]
这个是watermarker.js文件中第222行key没有定义的问题，我给提了pr

**Comment by kyoumeia** [comment]
现在有解决吗，我也遇到了

**Comment by FuLei-hub** [comment]
现在也没解决，搞笑

**Comment by So-For** [comment]
> 现在也没解决，搞笑

好像都不维护了- -

**Comment by SSDWGG** [comment]
一打包就废，还有别的水印插件可以用吗？

**Comment by So-For** [comment]
> 一打包就废，还有别的水印插件可以用吗？

自己手搓吧。我再网上找的使用vue指令添加水印，还可以
